// Code generated by goctl. DO NOT EDIT!
// Source: add.proto

package server

import (
	"context"

	"github.com/notes/go_zero/rpc/add"
	"github.com/notes/go_zero/rpc/internal/logic"
	"github.com/notes/go_zero/rpc/internal/svc"
)

type AddServer struct {
	svcCtx *svc.ServiceContext
}

func NewAddServer(svcCtx *svc.ServiceContext) *AddServer {
	return &AddServer{
		svcCtx: svcCtx,
	}
}

func (s *AddServer) Ping(ctx context.Context, in *add.Request) (*add.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
