// Code generated by goctl. DO NOT EDIT!
// Source: add.proto

//go:generate mockgen -destination ./add_mock.go -package addclient -source $GOFILE

package addclient

import (
	"context"

	"github.com/notes/go_zero/rpc/add"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	Request  = add.Request
	Response = add.Response

	Add interface {
		Ping(ctx context.Context, in *Request) (*Response, error)
	}

	defaultAdd struct {
		cli zrpc.Client
	}
)

func NewAdd(cli zrpc.Client) Add {
	return &defaultAdd{
		cli: cli,
	}
}

func (m *defaultAdd) Ping(ctx context.Context, in *Request) (*Response, error) {
	client := add.NewAddClient(m.cli.Conn())
	return client.Ping(ctx, in)
}
